name: Deploy Website with Proxmox Snapshot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Create Proxmox Snapshot
        run: |
          echo "Déclenchement du snapshot Proxmox..."
          # Générer un nom de snapshot unique contenant le numéro du job GitHub Actions
          SNAPSHOT_NAME="pre_deploy_job_${{ github.run_number }}"
          
          # Requête API à Proxmox en ignorant la validation SSL expirée (-k / --insecure)
          curl -k -X POST \
            -H "Authorization: PVEAPIToken=${{ secrets.PROXMOX_TOKEN_ID }}=${{ secrets.PROXMOX_TOKEN_SECRET }}" \
            -d "snapname=${SNAPSHOT_NAME}" \
            -d "description=Snapshot automatique créé par GitHub Actions avant le déploiement du site." \
            "${{ secrets.PROXMOX_API_URL }}/nodes/${{ secrets.PROXMOX_NODE }}/lxc/${{ secrets.PROXMOX_VMID }}/snapshot"
          
          # Pause de 10 secondes pour laisser le temps à Proxmox d'initier le snapshot

          sleep 10
          zabbix_sender -z 192.168.72.112 \
            -s "Web-Server-Prod" \
            -k snapshot.status \
            -o "Snapshot pre_deploy_job_${{ github.run_number }} créé"
          sleep 30

      - name: Deploy files to Apache directory
        run: |
          set -eux
          echo "Déploiement du site internet sur Apache..."
          pwd
          ls -lah
         # Copie sécurisée des fichiers
          cp -r * /var/www/html/
          cp -rv . /var/www/html/

          ls -lah /var/www/html
          # S'assurer que les permissions du dossier web restent correctes
          chmod -R 775 /var/www/html/

          #NOTIFICATION_Telegram
          
      - name: Notify Zabbix of Deployment Status
        if: always()
        run: |
          ZABBIX_SERVER="192.168.72.112"
          HOST_NAME="Web-Server-Prod"
        
          if [[ "${{ job.status }}" == "success" ]]; then
          # On envoie 1 (Succès) et le message
            zabbix_sender -z $ZABBIX_SERVER -s "$HOST_NAME" -k deploy.result -o 1
            zabbix_sender -z $ZABBIX_SERVER -s "$HOST_NAME" -k deploy.status -o "Succès : Version ${{ github.sha }} par ${{ github.actor }}"
          else
          # On envoie 0 (Échec) et le message
            zabbix_sender -z $ZABBIX_SERVER -s "$HOST_NAME" -k deploy.result -o 0
            zabbix_sender -z $ZABBIX_SERVER -s "$HOST_NAME" -k deploy.status -o "ERREUR : Le déploiement ${{ github.run_number }} a échoué"
          fi
